config/routes.rb
Seo::Engine.routes.draw do
  resources :meta_contents


  resources :permanent_redirects
end

app/models/seo/circular_redirect.rb
module Seo
  module CircularRedirect
    def valid_redirect?(origin, destination, record_klass)
      return false if record_klass.exists?(origin_id: destination, destination_id: origin)
      return false if chain_has_no_end?(origin, destination, record_klass)
      return true
    end

    private

    def chain_has_no_end?(origin, destination, record_klass)
      @destination_id = destination.to_i

      circular = loop do
        chain_link = record_klass.where(origin_id: @destination_id)
        break false if chain_link.empty?

        @destination_id = chain_link[0].destination_id.to_i
        break true if origin.to_i == @destination_id
      end

      !!circular
    end
  end
end

app/models/seo/circular_redirect/validator.rb
module Seo
  module CircularRedirect
    class Validator < ActiveModel::Validator
      include CircularRedirect

      def validate(record)
        unless valid_redirect?(record.origin_id, record.destination_id, PermanentRedirect)
          record.errors.add(:base, "This redirect is circular, it links to another redirect, creating an infinite redirection, please address.")
        end
      end
    end
  end
end

app/models/seo/infinite_redirect.rb
module Seo
  module InfiniteRedirect
    def valid_redirect?(origin, destination)
      origin.to_s != destination.to_s
    end
  end
end

app/models/seo/infinite_redirect/validator.rb
module Seo
  module InfiniteRedirect
    class Validator < ActiveModel::Validator
      include InfiniteRedirect

      def validate(record)
        unless valid_redirect?(record.origin_id, record.destination_id)
          record.errors.add(:destination_id, "must be different from the origin")
        end
      end
    end
  end
end

app/models/seo/meta_content.rb
module Seo
  class MetaContent < ActiveRecord::Base
    attr_accessible :meta_description, :meta_keywords, :meta_title, :resource_id, :resource_type

    validates_presence_of :resource_id, :resource_type
    validates_uniqueness_of :resource_id, scope: :resource_type, message: "has already been used"

    def resource_title
      resource = resource_type.constantize.find(resource_id)
      resource.send(resource.seo_resource_title)
    end
  end
end

app/models/seo/permanent_redirect.rb
module Seo
  class PermanentRedirect < ActiveRecord::Base
    include ActiveModel::Validations

    attr_accessible :destination_id, :origin_id

    validates :origin_id, uniqueness: true, presence: true
    validates :destination_id, uniqueness: true, presence: true
    validates_with InfiniteRedirect::Validator
    validates_with CircularRedirect::Validator
  end
end

app/controllers/seo/application_controller.rb
module Seo
  class ApplicationController < ActionController::Base
  end
end

app/controllers/seo/meta_contents_controller.rb
require_dependency "seo/application_controller"

module Seo
  class MetaContentsController < ApplicationController
    # GET /meta_contents
    # GET /meta_contents.json
    def index
      @meta_contents = MetaContent.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @meta_contents }
      end
    end
  
    # GET /meta_contents/1
    # GET /meta_contents/1.json
    def show
      @meta_content = MetaContent.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @meta_content }
      end
    end
  
    # GET /meta_contents/new
    # GET /meta_contents/new.json
    def new
      @meta_content = MetaContent.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @meta_content }
      end
    end
  
    # GET /meta_contents/1/edit
    def edit
      @meta_content = MetaContent.find(params[:id])
    end
  
    # POST /meta_contents
    # POST /meta_contents.json
    def create
      @meta_content = MetaContent.new(params[:meta_content])
  
      respond_to do |format|
        if @meta_content.save
          format.html { redirect_to @meta_content, notice: 'Meta content was successfully created.' }
          format.json { render json: @meta_content, status: :created, location: @meta_content }
        else
          format.html { render action: "new" }
          format.json { render json: @meta_content.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PUT /meta_contents/1
    # PUT /meta_contents/1.json
    def update
      @meta_content = MetaContent.find(params[:id])
  
      respond_to do |format|
        if @meta_content.update_attributes(params[:meta_content])
          format.html { redirect_to @meta_content, notice: 'Meta content was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @meta_content.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /meta_contents/1
    # DELETE /meta_contents/1.json
    def destroy
      @meta_content = MetaContent.find(params[:id])
      @meta_content.destroy
  
      respond_to do |format|
        format.html { redirect_to meta_contents_url }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/seo/permanent_redirects_controller.rb
require_dependency "seo/application_controller"

module Seo
  class PermanentRedirectsController < ApplicationController
    # GET /permanent_redirects
    # GET /permanent_redirects.json
    def index
      @permanent_redirects = PermanentRedirect.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @permanent_redirects }
      end
    end
  
    # GET /permanent_redirects/1
    # GET /permanent_redirects/1.json
    def show
      @permanent_redirect = PermanentRedirect.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @permanent_redirect }
      end
    end
  
    # GET /permanent_redirects/new
    # GET /permanent_redirects/new.json
    def new
      @permanent_redirect = PermanentRedirect.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @permanent_redirect }
      end
    end
  
    # GET /permanent_redirects/1/edit
    def edit
      @permanent_redirect = PermanentRedirect.find(params[:id])
    end
  
    # POST /permanent_redirects
    # POST /permanent_redirects.json
    def create
      @permanent_redirect = PermanentRedirect.new(params[:permanent_redirect])
  
      respond_to do |format|
        if @permanent_redirect.save
          format.html { redirect_to @permanent_redirect, notice: 'Permanent redirect was successfully created.' }
          format.json { render json: @permanent_redirect, status: :created, location: @permanent_redirect }
        else
          format.html { render action: "new" }
          format.json { render json: @permanent_redirect.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PUT /permanent_redirects/1
    # PUT /permanent_redirects/1.json
    def update
      @permanent_redirect = PermanentRedirect.find(params[:id])
  
      respond_to do |format|
        if @permanent_redirect.update_attributes(params[:permanent_redirect])
          format.html { redirect_to @permanent_redirect, notice: 'Permanent redirect was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @permanent_redirect.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /permanent_redirects/1
    # DELETE /permanent_redirects/1.json
    def destroy
      @permanent_redirect = PermanentRedirect.find(params[:id])
      @permanent_redirect.destroy
  
      respond_to do |format|
        format.html { redirect_to permanent_redirects_url }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/seo/application_helper.rb
module Seo
  module ApplicationHelper
  end
end

app/helpers/seo/meta_contents_helper.rb
module Seo
  module MetaContentsHelper
    def resource_type_select_options
      registered_models
    end

    def resource_select_options_by_type
      collections = {}
      registered_models.each do |model_klass|
        collections[model_klass.to_sym] = model_records(model_klass)
      end
      collections
    end

    private

    def registered_models
      ::Seo::ActsAsSeoContent.registered_models
    end

    def model_records(model_klass)
      model_klass.constantize.all.map do |instance|
        title_attr = instance.seo_resource_title
        [instance.send(title_attr), instance.id]
      end
    end
  end
end

app/helpers/seo/navigation_helper.rb
module Seo
  module NavigationHelper
    # Usage:
    #
    # nav_item(:resource_path)
    # nav_item(:resource_path, "Custom Title")
    #
    def nav_item(path, title=false)
      path_name = path.to_s.gsub('_path', '')

      content_tag :li, class: nav_css_class(path_name) do
        content_tag :a, href: public_send(path) do
          title || path_name.titleize
        end
      end
    end

    private

    def nav_css_class(path)
      'active' if resolves_to_current_controller?(path)
    end

    def resolves_to_current_controller?(path)
      controller.url_options[:_path_segments][:controller] == named_route_controller(path.to_s.gsub('_path', ''))
    end

    def named_route_controller(named_route)
      ::Seo::Engine.routes.named_routes.routes[named_route.to_sym].defaults[:controller]
    end
  end
end

app/helpers/seo/permanent_redirect_helper.rb
module Seo
  module PermanentRedirectHelper
    def page_select_options
      ::Seo.page_class.order(:title).all.map {|p| [p.title, p.id] }
    end

    def page_title(id)
      ::Seo.page_class.find(id).title
    end
  end
end

app/views/seo/meta_contents/_form.html.erb
<%= form_for(@meta_content, html: { css: 'form-horizontal', role: 'form' }) do |f| %>
  <% if @meta_content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meta_content.errors.count, "error") %> prohibited this meta content from being saved:</h2>
      <% @meta_content.errors.full_messages.each do |msg| %>
      <p class="text-danger bg-danger"><%= msg %></p>
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :resource_type %><br />
    <%= f.select :resource_type, resource_type_select_options %>
  </div>

  <div class="form-group">
    <%= f.label :resource_id %><br />
    <% resource_select_options_by_type.each_pair do |klass,choices| %>
      <div class="resource-select-by-type" data-klass="<%= klass %>">
	<%= select "#{klass.downcase}_resource", "resource_ids", choices, include_blank: true %>
      </div>
    <% end %>
    <%= f.hidden_field :resource_id %>
  </div>

  <div class="form-group">
    <%= f.label :meta_title %><br />
    <%= f.text_field :meta_title %>
  </div>

  <div class="form-group">
    <%= f.label :meta_description %><br />
    <%= f.text_area :meta_description %>
  </div>

  <div class="form-group">
    <%= f.label :meta_keywords %><br />
    <%= f.text_area :meta_keywords %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/seo/meta_contents/edit.html.erb
<h1>Editing Meta Tags</h1>

<%= render 'form' %>

<%= link_to 'Show', @meta_content %> |
<%= link_to 'Back', meta_contents_path %>

app/views/seo/meta_contents/index.html.erb
<h1 class="page-header">Listing Resource Meta Tags</h1>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
	<th>Resource</th>
	<th>Resource type</th>
	<th>Meta title</th>
	<th>Meta description</th>
	<th>Meta keywords</th>
	<th></th>
	<th></th>
	<th></th>
      </tr>
    </thead>
    <tbody>
      <% @meta_contents.each do |meta_content| %>
      <tr>
	<td><%= meta_content.resource_title %></td>
	<td><%= meta_content.resource_type %></td>
	<td><%= meta_content.meta_title %></td>
	<td><%= meta_content.meta_description %></td>
	<td><%= meta_content.meta_keywords %></td>
	<td><%= link_to 'Show', meta_content, class: 'btn btn-default' %></td>
	<td><%= link_to 'Edit', edit_meta_content_path(meta_content), class: 'btn btn-default' %></td>
	<td><%= link_to 'Destroy', meta_content, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

<br />

<%= link_to 'New Meta content', new_meta_content_path, class: 'btn btn-primary' %>

app/views/seo/meta_contents/new.html.erb
<h1>New Meta Tags</h1>

<%= render 'form' %>

<%= link_to 'Back', meta_contents_path, class: 'btn btn-default' %>

app/views/seo/meta_contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Resource:</b>
  <%= @meta_content.resource_title %>
</p>

<p>
  <b>Resource type:</b>
  <%= @meta_content.resource_type %>
</p>

<p>
  <b>Meta title:</b>
  <%= @meta_content.meta_title %>
</p>

<p>
  <b>Meta description:</b>
  <%= @meta_content.meta_description %>
</p>

<p>
  <b>Meta keywords:</b>
  <%= @meta_content.meta_keywords %>
</p>


<%= link_to 'Edit', edit_meta_content_path(@meta_content) %> |
<%= link_to 'Back', meta_contents_path %>